from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)


def generate_report(
    filename,
    district,
    stage,
    category
):

    try:

        doc = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        content = []

        # Title

        content.append(
            Paragraph(
                "JALNETRA Groundwater Assessment Report",
                styles["Title"]
            )
        )

        content.append(
            Spacer(1, 20)
        )

        # Report Details

        content.append(
            Paragraph(
                f"<b>District:</b> {district}",
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 10)
        )

        content.append(
            Paragraph(
                f"<b>Groundwater Stage:</b> {stage}",
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 10)
        )

        content.append(
            Paragraph(
                f"<b>Groundwater Category:</b> {category}",
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 20)
        )

        # Recommendation

        if str(category).lower() == "safe":

            recommendation = (
                "Groundwater resources are currently in a safe condition."
            )

        elif "semi" in str(category).lower():

            recommendation = (
                "Groundwater extraction should be monitored carefully."
            )

        elif "critical" in str(category).lower():

            recommendation = (
                "Groundwater conservation measures are strongly recommended."
            )

        else:

            recommendation = (
                "Groundwater extraction exceeds sustainable limits."
            )

        content.append(
            Paragraph(
                f"<b>Recommendation:</b> {recommendation}",
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 20)
        )

        content.append(
            Paragraph(
                "Generated by JALNETRA AI Groundwater Intelligence System",
                styles["Italic"]
            )
        )

        doc.build(content)

        return filename

    except Exception as e:

        print("Report Error:", e)

        return None